### ISSUE TITLE
Accounts Plan View

### ISSUE THREAD

**Issue by gumiz** [gumiz/finLite#1]

**Comment by sofcia** [comment]
tu mam cos pisac?

**Comment by gumiz** [comment]
mozesz dodawac zadania nowe
albo komentowac istniejace
ale na razie nic tam nie robie

2015-04-23 21:41 GMT+02:00 sofcia notifications@github.com:

> tu mam cos pisac?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gumiz/finLite/issues/1#issuecomment-95695836.

## 

Pozdrawiam,
Michał Górny

**Comment by gumiz** [comment]
done
